# Generated by Django 2.2.4 on 2019-09-17 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='punchlog',
            old_name='punch_latitude',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='punchlog',
            old_name='punch_longitude',
            new_name='longitude',
        ),
    ]
