# Generated by Django 2.2.4 on 2019-08-23 06:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('member', '0003_agencyapplication'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AgencyApplication',
            new_name='OrganizationApplication',
        ),
    ]
