# Generated by Django 2.2.4 on 2019-08-23 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_auto_20190823_0639'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organizationapplication',
            options={'verbose_name': 'Organization application', 'verbose_name_plural': 'Organization applications'},
        ),
    ]
