# Generated by Django 2.2.4 on 2019-08-15 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='golfclub',
            name='caddie_fee',
            field=models.DecimalField(decimal_places=2, default=1, help_text='THB', max_digits=11, verbose_name='Caddie fee'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='golfclub',
            name='cart_fee',
            field=models.DecimalField(decimal_places=2, default=1, help_text='THB', max_digits=11, verbose_name='Cart fee'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='golfclub',
            name='cart_rental_required',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Cart rental required'),
        ),
        migrations.AddField(
            model_name='golfclub',
            name='hole',
            field=models.IntegerField(choices=[(0, '18 Holes'), (1, '9 Holes')], db_index=True, default=0, verbose_name='No. of Holes'),
        ),
    ]
