# Generated by Django 2.2.4 on 2019-08-23 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='clubproduct',
            unique_together={('season', 'day_of_week', 'slot')},
        ),
    ]
