# Generated by Django 2.2.4 on 2019-08-24 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='high_season',
            field=models.IntegerField(default=3075, verbose_name='High season'),
        ),
    ]
