# Generated by Django 2.2.4 on 2019-08-16 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Agency name'),
        ),
    ]
