# Generated by Django 2.2.4 on 2019-08-25 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.IntegerField(choices=[(0, 'payment pending'), (1, 'payment completed'), (2, 'under review'), (3, 'payment verified'), (4, 'shipped'), (5, 'refund requested'), (6, 'refund pending'), (7, 'refunded'), (8, 'refunded'), (9, 'voided')], db_index=True, default=0, verbose_name='Booking status'),
        ),
    ]
