# Generated by Django 2.2.4 on 2019-09-05 16:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('account', models.IntegerField(choices=[(0, 'Kasikorn Bank'), (1, 'Bangkok Bank'), (2, 'Siam Commercial Bank'), (3, 'Ayudhya Bank'), (4, 'Krungthai Bank')], db_index=True, default=0, verbose_name='Bank account')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Paid amount')),
                ('received', models.DateTimeField(verbose_name='Received date')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='golf.Booking', verbose_name='Booking')),
            ],
            options={
                'verbose_name': 'Booking payment',
                'verbose_name_plural': 'Booking payments',
            },
        ),
        migrations.CreateModel(
            name='BookingChangeLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('log', models.TextField(verbose_name='Changelog')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='Memo')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='golf.Booking', verbose_name='Booking')),
            ],
            options={
                'verbose_name': 'Booking change log',
                'verbose_name_plural': 'Booking change logs',
            },
        ),
    ]
