# Generated by Django 2.2.4 on 2019-09-09 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingteeofftime',
            name='status',
            field=models.IntegerField(choices=[(0, 'Time offered'), (1, 'Time accepted'), (2, 'Time rejected'), (3, 'Time revoked'), (4, 'Time voided')], db_index=True, default=0, verbose_name='Tee-off time status'),
        ),
    ]
