# Generated by Django 2.2.4 on 2019-08-15 18:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('season', models.IntegerField(choices=[(0, 'Low season'), (1, 'High season')], db_index=True, default=1, verbose_name='High/Low Season')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Weekday'), (1, 'Weekend')], db_index=True, default=0, verbose_name='Day of week')),
                ('slot', models.IntegerField(choices=[(0, 'Twilight'), (1, 'Morning'), (2, 'Daytime'), (3, 'Night')], db_index=True, default=0, verbose_name='Time slot')),
                ('fee', models.DecimalField(decimal_places=2, help_text='THB', max_digits=11, verbose_name='Fee amount')),
                ('cost', models.DecimalField(decimal_places=2, help_text='THB', max_digits=11, verbose_name='Cost amount')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='golf.TravelAgent', verbose_name='Travel agent')),
            ],
            options={
                'verbose_name': 'Price table',
                'verbose_name_plural': 'Price tables',
            },
        ),
    ]
