# Generated by Django 2.2.4 on 2019-09-09 08:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingTeeOffTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('tee_off_time', models.TimeField(verbose_name='Tee-off time')),
                ('offered', models.BooleanField(db_index=True, default=False, verbose_name='Tee-off time offered')),
                ('accepted', models.BooleanField(db_index=True, default=False, verbose_name='Tee-off time accepted')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='golf.Booking', verbose_name='Booking')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
