# Generated by Django 2.2.4 on 2019-09-05 16:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0002_bookingchangelog_bookingpayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingAccountReceivable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Unpaid mount')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='golf.Booking', verbose_name='Booking')),
            ],
            options={
                'verbose_name': 'Booking account receivable',
                'verbose_name_plural': 'Booking accounts receivable',
            },
        ),
    ]
