# Generated by Django 2.2.4 on 2019-08-25 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0002_booking_club'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='people',
            field=models.IntegerField(verbose_name='No. of people'),
        ),
    ]
