# Generated by Django 2.2.4 on 2019-08-25 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0002_auto_20190825_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.IntegerField(choices=[(0, 'payment pending'), (1, 'payment completed'), (2, 'payment verified'), (3, 'shipped'), (4, 'refund requested'), (5, 'refund pending'), (6, 'refunded'), (7, 'refunded'), (8, 'voided')], db_index=True, default=0, verbose_name='Booking status'),
        ),
    ]
