# Generated by Django 2.2.4 on 2019-08-25 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0002_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Confirmed'), (2, 'Shipped')], db_index=True, default=0, verbose_name='Booking status'),
        ),
    ]
