# Generated by Django 2.2.4 on 2019-09-09 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0002_bookingteeofftime'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookingteeofftime',
            options={'verbose_name': 'Tee-off time', 'verbose_name_plural': 'Tee-off time'},
        ),
    ]
