# Generated by Django 2.2.4 on 2019-09-11 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0002_bookingcounter'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingcounter',
            name='club',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='golf.Club', verbose_name='Golf club'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='bookingcounter',
            unique_together={('club', 'booking_date')},
        ),
    ]
