# Generated by Django 2.2.4 on 2019-09-11 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0002_auto_20190911_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.IntegerField(choices=[(0, 'order opened'), (1, 'order pending'), (2, 'payment pending'), (3, 'order complete'), (4, 'order offered'), (5, 'order voided'), (6, 'refund requested'), (7, 'refund pending'), (8, 'order refunded(original)'), (9, 'order refunded(reverse)')], db_index=True, default=0, verbose_name='Booking status'),
        ),
    ]
