# Generated by Django 2.2.4 on 2019-08-16 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0002_auto_20190816_0153'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='bookable_days',
            field=models.IntegerField(db_index=True, default=90, verbose_name='Bookable days'),
        ),
        migrations.AddField(
            model_name='agency',
            name='cancellable_days',
            field=models.IntegerField(db_index=True, default=3, verbose_name='Cancellable days'),
        ),
        migrations.AddField(
            model_name='agency',
            name='due_days',
            field=models.IntegerField(db_index=True, default=1, verbose_name='Payment due days'),
        ),
    ]
