# Generated by Django 2.2.4 on 2019-09-10 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0002_auto_20190909_1917'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bookingteeofftime',
            unique_together={('booking', 'tee_off_time')},
        ),
    ]
