# Generated by Django 2.2.4 on 2019-09-06 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0002_auto_20190906_0034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='booking_person',
        ),
        migrations.AddField(
            model_name='booking',
            name='first_name',
            field=models.CharField(default='-', max_length=255, verbose_name='First name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='last_name',
            field=models.CharField(default='-', max_length=255, verbose_name='Last name'),
            preserve_default=False,
        ),
    ]
