# Generated by Django 2.2.4 on 2019-08-24 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0003_holiday'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='holiday',
            unique_together={('year', 'holiday', 'country')},
        ),
    ]
