# Generated by Django 2.2.4 on 2019-09-09 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0003_auto_20190909_1513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingteeofftime',
            name='accepted',
        ),
        migrations.RemoveField(
            model_name='bookingteeofftime',
            name='offered',
        ),
        migrations.AddField(
            model_name='bookingteeofftime',
            name='status',
            field=models.IntegerField(choices=[(0, 'Time offered'), (1, 'Time accepted'), (2, 'Time rejected'), (3, 'Time revoked')], db_index=True, default=0, verbose_name='Tee-off time status'),
        ),
    ]
