# Generated by Django 2.2.4 on 2019-09-08 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0003_booking_tee_off_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_removed',
            field=models.BooleanField(default=False),
        ),
    ]
