# Generated by Django 2.2.4 on 2019-08-23 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0003_auto_20190823_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='THB', max_digits=11, verbose_name='Amount'),
        ),
        migrations.CreateModel(
            name='AgencyClubProductListMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee', models.DecimalField(decimal_places=2, help_text='THB', max_digits=11, verbose_name='Fee amount')),
                ('position', models.IntegerField(verbose_name='Position')),
                ('agency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='golf.Agency', verbose_name='Agency')),
                ('product_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='golf.ClubProductListMembership', verbose_name='Product list')),
            ],
            options={
                'verbose_name': 'Agency product list membership',
                'verbose_name_plural': 'Agency product list membership',
                'unique_together': {('agency', 'product_list')},
            },
        ),
    ]
