# Generated by Django 2.2.4 on 2019-08-23 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0003_golfclubproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='golfclubproduct',
            name='slot',
            field=models.IntegerField(choices=[(0, 'Morning'), (1, 'Daytime'), (2, 'Twilight'), (3, 'Night')], db_index=True, default=2, verbose_name='Time slot'),
        ),
    ]
