# Generated by Django 2.2.4 on 2019-09-10 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0003_auto_20190910_2225'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookingteeofftime',
            options={'ordering': ('-tee_off_time',), 'verbose_name': 'Tee-off time', 'verbose_name_plural': 'Tee-off time'},
        ),
    ]
