# Generated by Django 2.2.4 on 2019-09-12 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0003_auto_20190912_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingcounter',
            name='day_of_week',
            field=models.IntegerField(choices=[(0, 'High/Weekday'), (1, 'High/Weekend'), (2, 'Low/Weekday'), (3, 'Low/Weekend')], db_index=True, default=0, verbose_name='Season / Day of week'),
        ),
    ]
