# Generated by Django 2.2.4 on 2019-08-23 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0004_auto_20190823_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='products',
            field=models.ManyToManyField(through='golf.AgencyClubProductListMembership', to='golf.ClubProductListMembership'),
        ),
    ]
