# Generated by Django 2.2.4 on 2019-08-25 10:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0004_auto_20190825_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID'),
        ),
    ]
