# Generated by Django 2.2.4 on 2019-09-12 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0004_auto_20190912_0912'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='max_high_weekday',
            field=models.PositiveIntegerField(default=0, verbose_name='Max # of High/Weekday'),
        ),
        migrations.AddField(
            model_name='club',
            name='max_high_weekend',
            field=models.PositiveIntegerField(default=0, verbose_name='Max # of High/Weekend'),
        ),
        migrations.AddField(
            model_name='club',
            name='max_low_weekday',
            field=models.PositiveIntegerField(default=0, verbose_name='Max # of Low/Weekday'),
        ),
        migrations.AddField(
            model_name='club',
            name='max_low_weekend',
            field=models.PositiveIntegerField(default=0, verbose_name='Max # of Low/Weekday'),
        ),
    ]
