# Generated by Django 2.2.4 on 2019-09-08 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0004_booking_is_removed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.IntegerField(choices=[(0, 'order made'), (1, 'order pending'), (2, 'payment_pending'), (3, 'voucher issued'), (4, 'order revoked'), (5, 'refund requested'), (6, 'refund pending'), (7, 'order refunded(original)'), (8, 'order refunded(reverse)'), (9, 'order voided')], db_index=True, default=1, verbose_name='Booking status'),
        ),
    ]
