# Generated by Django 2.2.4 on 2019-08-24 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0004_auto_20190824_0742'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='country',
            field=models.IntegerField(choices=[(1, 'Thailand'), (2, 'South Korea'), (3, 'Japan'), (4, 'China')], db_index=True, default=1, verbose_name='Country code'),
        ),
    ]
