# Generated by Django 2.2.4 on 2019-08-24 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0005_club_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holiday',
            name='year',
            field=models.IntegerField(db_index=True, verbose_name='Holiday year'),
        ),
    ]
