# Generated by Django 2.2.4 on 2019-09-12 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0005_auto_20190912_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='max_low_weekend',
            field=models.PositiveIntegerField(default=0, verbose_name='Max # of Low/Weekend'),
        ),
    ]
