# Generated by Django 2.2.4 on 2019-08-23 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0005_auto_20190823_1046'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PriceTable',
        ),
    ]
