# Generated by Django 2.2.4 on 2019-09-09 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0006_auto_20190908_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.IntegerField(choices=[(0, 'order made'), (1, 'order pending'), (2, 'payment_pending'), (3, 'voucher issued'), (4, 'order revoked'), (5, 'order voided'), (6, 'refund requested'), (7, 'refund pending'), (8, 'order refunded(original)'), (9, 'order refunded(reverse)')], db_index=True, default=0, verbose_name='Booking status'),
        ),
    ]
