# Generated by Django 2.2.4 on 2019-08-24 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0006_auto_20190824_0940'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='holiday',
            unique_together={('holiday', 'country')},
        ),
        migrations.RemoveField(
            model_name='holiday',
            name='year',
        ),
    ]
