# Generated by Django 2.2.4 on 2019-08-23 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0006_delete_pricetable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='golfclubproduct',
            name='time_end',
        ),
        migrations.RemoveField(
            model_name='golfclubproduct',
            name='time_start',
        ),
        migrations.CreateModel(
            name='ProductListMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(verbose_name='Start time')),
                ('end_time', models.TimeField(verbose_name='End time')),
                ('list_price', models.DecimalField(decimal_places=2, help_text='THB', max_digits=11, verbose_name='List price')),
                ('position', models.IntegerField(verbose_name='Position')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='golf.GolfClub', verbose_name='Golf club')),
                ('product_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='golf.GolfClubProduct', verbose_name='Product list')),
            ],
            options={
                'verbose_name': 'Product list membership',
                'verbose_name_plural': 'Product list membership',
            },
        ),
        migrations.AddField(
            model_name='golfclub',
            name='products',
            field=models.ManyToManyField(through='golf.ProductListMembership', to='golf.GolfClubProduct'),
        ),
    ]
