# Generated by Django 2.2.4 on 2019-08-23 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0007_auto_20190823_1205'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productlistmembership',
            unique_together={('product', 'product_list')},
        ),
    ]
