# Generated by Django 2.2.4 on 2019-08-23 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0008_auto_20190823_1225'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productlistmembership',
            old_name='product',
            new_name='club',
        ),
        migrations.AlterUniqueTogether(
            name='productlistmembership',
            unique_together={('club', 'product_list')},
        ),
    ]
